image: node:latest

stages:
  - install
  - test
  - deploy # Jobs placed in build-stage will run last after test-jobs

install:
  stage: install
  script:
    - apt update
    - apt-get --assume-yes install software-properties-common
    - add-apt-repository ppa:longsleep/golang-backports
    - apt install --assume-yes golang-go

test:
  stage: test
  script: 
    - mysql -u root && create database wallet_service


deploy:
  stage: deploy
  script:
    - mkdir ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - touch ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa # Required permission by ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - touch ~/.ssh/id_rsa.pub
    - chmod 600 ~/.ssh/id_rsa.pub # Required permission by ssh
    - echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
    - apt-get update
    - apt-get install --assume-yes rsync
    - rsync --archive --delete --exclude='.git' --exclude='.config' --exclude='node_modules' . order@34.67.42.245:two-phase-commit
    - ssh order@34.67.42.245 "echo $IP_ADDRESSES  > two-phase-commit/addresses"
    - ssh order@34.67.42.245 systemctl --user restart order
    - rsync --archive --delete --exclude='.git' --exclude='.config' --exclude='node_modules' . wallet@35.202.15.128:two-phase-commit
    - ssh wallet@35.202.15.128 "echo $IP_ADDRESSES  > two-phase-commit/addresses"
    - ssh wallet@35.202.15.128 systemctl --user restart wallet
    - rsync --archive --delete --exclude='.git' --exclude='.config' --exclude='node_modules' . orc@35.223.240.171:two-phase-commit
    - ssh orc@35.223.240.171 "echo $IP_ADDRESSES  > two-phase-commit/addresses"
    - ssh orc@35.223.240.171 systemctl --user restart orc
  only:
    - master
